const JSON_HEADERS={"content-type":"application/json; charset=utf-8","cache-control":"no-store"};
const json=(body,status=200)=>new Response(JSON.stringify(body),{status,headers:JSON_HEADERS});
const now=()=>new Date().toISOString();
const randomCode=(n=6)=>{const chars="ABCDEFGHJKLMNPQRSTUVWXYZ23456789";let s="";const a=new Uint32Array(n);crypto.getRandomValues(a);for(const x of a)s+=chars[x%chars.length];return s};
const randomToken=()=>crypto.randomUUID().replaceAll("-","")+crypto.randomUUID().replaceAll("-","");
async function sha256(value){const bytes=new TextEncoder().encode(value);const digest=await crypto.subtle.digest("SHA-256",bytes);return [...new Uint8Array(digest)].map(b=>b.toString(16).padStart(2,"0")).join("")}
async function parseBody(request){const len=Number(request.headers.get("content-length")||0);if(len>300000)throw new Error("PAYLOAD_TOO_LARGE");return await request.json()}
function cleanSnapshot(value){if(!value||typeof value!=="object"||Array.isArray(value))throw new Error("SNAPSHOT_INVALID");const text=JSON.stringify(value);if(text.length>250000)throw new Error("PAYLOAD_TOO_LARGE");return text}
async function auth(request,env){const h=request.headers.get("authorization")||"";const token=h.startsWith("Bearer ")?h.slice(7):"";if(!token)return null;const hash=await sha256(token);return await env.DB.prepare("SELECT m.household_id,h.name,h.invite_code FROM members m JOIN households h ON h.id=m.household_id WHERE m.token_hash=? AND m.revoked_at IS NULL").bind(hash).first()}
async function createHousehold(request,env){const body=await parseBody(request);const name=String(body.name||"Casa condivisa").trim().slice(0,40)||"Casa condivisa";const payload=cleanSnapshot(body.snapshot||{});const id=crypto.randomUUID();let inviteCode;for(let i=0;i<8;i++){inviteCode=randomCode();const found=await env.DB.prepare("SELECT 1 FROM households WHERE invite_code=?").bind(inviteCode).first();if(!found)break}const token=randomToken(),tokenHash=await sha256(token),created=now();await env.DB.batch([env.DB.prepare("INSERT INTO households(id,name,invite_code,created_at,updated_at) VALUES(?,?,?,?,?)").bind(id,name,inviteCode,created,created),env.DB.prepare("INSERT INTO members(id,household_id,token_hash,created_at) VALUES(?,?,?,?)").bind(crypto.randomUUID(),id,tokenHash,created),env.DB.prepare("INSERT INTO snapshots(household_id,revision,payload,updated_at) VALUES(?,?,?,?)").bind(id,1,payload,created)]);return json({householdId:id,householdName:name,inviteCode,token,revision:1})}
async function joinHousehold(request,env){const body=await parseBody(request);const inviteCode=String(body.inviteCode||"").trim().toUpperCase();const house=await env.DB.prepare("SELECT id,name,invite_code FROM households WHERE invite_code=?").bind(inviteCode).first();if(!house)return json({error:"Codice non valido."},404);const token=randomToken(),tokenHash=await sha256(token),created=now();await env.DB.prepare("INSERT INTO members(id,household_id,token_hash,created_at) VALUES(?,?,?,?)").bind(crypto.randomUUID(),house.id,tokenHash,created).run();const snap=await env.DB.prepare("SELECT revision,payload FROM snapshots WHERE household_id=?").bind(house.id).first();return json({householdId:house.id,householdName:house.name,inviteCode:house.invite_code,token,revision:snap?.revision||0,snapshot:JSON.parse(snap?.payload||"{}")})}
async function getSync(request,env,member){const snap=await env.DB.prepare("SELECT revision,payload,updated_at FROM snapshots WHERE household_id=?").bind(member.household_id).first();return json({revision:snap?.revision||0,snapshot:JSON.parse(snap?.payload||"{}"),updatedAt:snap?.updated_at||null})}
async function putSync(request,env,member){const body=await parseBody(request);const payload=cleanSnapshot(body.snapshot||{});const current=await env.DB.prepare("SELECT revision FROM snapshots WHERE household_id=?").bind(member.household_id).first();const revision=Number(current?.revision||0);if(Number(body.baseRevision||0)!==revision)return json({error:"CONFLICT",revision},409);const next=revision+1,updated=now();await env.DB.batch([env.DB.prepare("UPDATE snapshots SET revision=?,payload=?,updated_at=? WHERE household_id=?").bind(next,payload,updated,member.household_id),env.DB.prepare("UPDATE households SET updated_at=? WHERE id=?").bind(updated,member.household_id)]);return json({revision:next,updatedAt:updated})}
export default{async fetch(request,env){try{const url=new URL(request.url);if(url.pathname==="/api/health")return json({ok:true,service:"Scorta Casa Sync"});if(url.pathname==="/api/households"&&request.method==="POST")return await createHousehold(request,env);if(url.pathname==="/api/households/join"&&request.method==="POST")return await joinHousehold(request,env);if(url.pathname.startsWith("/api/")){const member=await auth(request,env);if(!member)return json({error:"TOKEN_INVALID"},401);if(url.pathname==="/api/sync"&&request.method==="GET")return await getSync(request,env,member);if(url.pathname==="/api/sync"&&request.method==="PUT")return await putSync(request,env,member);return json({error:"API non trovata"},404)}return env.ASSETS.fetch(request)}catch(error){const code=error?.message||"Errore interno";const status=code==="PAYLOAD_TOO_LARGE"?413:code==="SNAPSHOT_INVALID"?400:500;console.error(error);return json({error:code},status)}}};
